In [1]:
import numpy as np

In [2]:
a = np.zeros(10)

In [3]:
b = np.ones(10)

In [4]:
arrFives = b * 5

In [5]:
arrFives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(0, 1)

array([], shape=(0, 1), dtype=float64)

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
import pandas as pd

In [13]:
data = np.random.rand(1000000)

In [14]:
import time
start = time.time()
mean = np.mean(data)
end = time.time()
end-start

0.0019986629486083984

In [15]:
# pandas
start = time.time()
mean = pd.DataFrame(data).mean()
end = time.time()
end - start

0.02098846435546875