In [1]:
import numpy as np

In [2]:
# 1. numpy version
np.__version__

'1.26.4'

In [3]:
# 1. numpy congig
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [4]:
# 2. add two numpy arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1+arr2


array([5, 7, 9])

In [5]:
arr = np.array([1, 4, 5, 0, -8, 0, 0, 5, 0, 4, -9])

In [6]:
# 3. none element element is zero
arr[arr!=0]

array([ 1,  4,  5, -8,  5,  4, -9])

In [7]:
# 4. non-zero elements
arr[arr!=0]

array([ 1,  4,  5, -8,  5,  4, -9])

In [8]:
# 5.  check if finite
arr = np.array([4, 5, 7, 888888888888888, 0])
np.isfinite(arr)

array([ True,  True,  True,  True,  True])

In [64]:
# 6. element wise positive or negative infinity
np.isneginf(-np.inf)

True

In [10]:
np.isposinf(np.inf)

True

In [71]:
# 7.NAN of array
arr = np.array([4, 5, 7, np.nan, 0])
np.isnan(arr)

array([False, False, False,  True, False])

In [12]:
# 8. test whether complex, real number
arr = np.array([1+1j, 2+5j, 4, 7])
np.iscomplex(arr)

array([ True,  True, False, False])

In [13]:
arr = np.array([1+7j, 4.555, 2, 1j])
np.isreal(arr)

array([False,  True,  True, False])

In [14]:
#9. element wise comparison
arr1 = np.array([4, 2, 5])
arr2 = np.array([7, 2, 1])

np.greater(arr1, arr2)

array([False, False,  True])

In [15]:
np.greater_equal(arr1, arr2)

array([False,  True,  True])

In [16]:
np.less(arr1, arr2)

array([ True, False, False])

In [17]:
np.less_equal(arr1, arr2)

array([ True,  True, False])

In [18]:
#10. write a program to check size of memory occupied by array
arr = np.array([1, 7, 13, 105])
# arr.size # gives count of elements
arr.nbytes

16

In [19]:
#11.array of 10 zeros
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# array of 10 ones
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
# array of 10 fives
one = np.ones(10)
five = [one*5]

In [22]:
five

[array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])]

In [23]:
# 12. array from 30 to 70
arr2 = np.arange(30, 71)
arr2

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [24]:
# 13. even integers from 30 to 70
arr = np.arange(30, 71)
arr[arr%2==0]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [25]:
# 14 3x3 identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# 15. random number between 0 and 1
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [27]:
# 16. random number, standard normal distribution
np.random.randint(15)

10

In [28]:
# 17. 15 to 55, excluding 1st and last 
arr = np.arange(15, 56)
arr[1: -1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [29]:
# 18. 3x4 matrix
np.random.randint(13, size=( 3, 4))

array([[10,  6, 12,  9],
       [ 5,  6,  4,  2],
       [ 7,  1,  3,  7]])

In [30]:
# 19. vector of length 10 with values evenly distributed
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [31]:
# 20. 0-20, change sign of numbers in rnge 9-15
arr = np.arange(20)

In [32]:
# 21. create a vector of length 5 filled with arbitary integers from 0 to 10.
arr1 = np.linspace(0,10,5)
arr1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [72]:
#22. multiply values of two vectors
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,3,4])
arr1*arr2

array([ 5, 12,  9, 16])

In [73]:
#23. to create a 3x4 matrix with values from 10 to 21
np.random.randint(10,21,size=(3,4))

array([[10, 11, 10, 15],
       [13, 15, 18, 11],
       [11, 19, 17, 14]])

In [74]:
#24. find rows and columns
arr = np.array([[11,22,33,44,55],[23,45,67,89,78]])
rows,columns = arr.shape
rows

2

In [36]:
columns

5

In [37]:
#25. Identity matrix
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
#26. 10x10 matrix with border elements = 1, inside = 0
s = (10, 10)
arr = np.ones(s)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
# rows, columns
arr[1:9, 1:9]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [42]:
arr.diagonal(2)

array([2, 7])

In [43]:
np.fill_diagonal(arr, [1,2,3,4])

In [44]:
arr

array([[ 1,  1,  2,  3],
       [ 4,  2,  6,  7],
       [ 8,  9,  3, 11],
       [12, 13, 14,  4]])

In [45]:
# 27. 5x5 zero matrix; replace diagonal with 1, 2, 3, 4, 5
s = (5, 5)
zero = np.zeros(s)
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.fill_diagonal(zero, [1, 2, 3, 4, 5])

In [47]:
zero

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [48]:
# 28. 3D matrix with  arbitrary values
np.random.randint(50, size=(3, 3, 3))

array([[[ 6, 31, 39],
        [29, 13, 48],
        [11, 36, 27]],

       [[ 9, 47,  0],
        [28, 25, 16],
        [38, 40, 35]],

       [[30, 30, 24],
        [45, 26, 26],
        [43,  3, 27]]])

In [49]:
# 29. inner product of 2 vectors
a1 = np.array([2, 5, 4, 6])
a2 = np.array([10, 10, 10, 10])
np.inner(a1, a2)

170

In [50]:
# 30. sort array by row and column
a = np.array([[420, 1, 5, 44, 23, 8], [10, 1, 47, 8, 54, 9]]) 
a

array([[420,   1,   5,  44,  23,   8],
       [ 10,   1,  47,   8,  54,   9]])

In [76]:
# axis = 0 to sort by comparing values in column, row wise
x = np.sort(a, axis = 0)

In [52]:
a

array([[420,   1,   5,  44,  23,   8],
       [ 10,   1,  47,   8,  54,   9]])

In [53]:
x

array([[ 10,   1,   5,   8,  23,   8],
       [420,   1,  47,  44,  54,   9]])

In [54]:
y = np.sort(a, axis = 1)
y

array([[  1,   5,   8,  23,  44, 420],
       [  1,   8,   9,  10,  47,  54]])

In [55]:
# 31. greater than a number
arr = np.array([4, 5, 7, 5, 11, 80, 99])
greaterThan = arr[arr>10]
greaterThan

array([11, 80, 99])

In [56]:
# 32. replace elements greater than, equal, less than
arr = np.array([9, 8, 2, 6, 5, 1])
gt5 = arr[arr>5]
gt5

array([9, 8, 6])

In [57]:
arr[arr==5]=10
arr

array([ 9,  8,  2,  6, 10,  1])

In [58]:
lt5 = arr[arr<5]
lt5

array([2, 1])

In [59]:
# 33. equal shape, dtype
arr = np.arange(16).reshape(4, 4)

In [60]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
# 34. 3d varray: 3, 4, 5
threeD = np.random.randint(50, size=(3, 4, 5))

In [62]:
threeD

array([[[30, 49, 37,  0, 23],
        [27, 33, 10,  0,  9],
        [ 3, 46, 47,  3, 30],
        [26, 18, 27, 39, 25]],

       [[30, 29, 18,  9, 18],
        [19, 39, 17,  9,  4],
        [11,  4, 46, 33, 15],
        [ 8, 31, 34, 28, 19]],

       [[12,  8, 31, 49, 24],
        [29,  3, 40, 24, 44],
        [48, 28,  8,  6, 17],
        [37, 41, 15, 36, 33]]])

In [63]:
# 35. multiply 2 arrays
a1 = np.array([4, 5, 6, 7])
a2 = np.array([7, 2, 1, 4])
a1 * a2

array([28, 10,  6, 28])