In [2]:
import numpy as np

In [19]:
cont = np.genfromtxt('data_complex.csv', delimiter=';', comments='#')

In [20]:
cont

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
contxt = np.genfromtxt('data_complex.txt', delimiter=',', comments='#')

In [18]:
contxt

array([nan, nan, nan])

In [24]:
a = np.random.randint(1, 10, size = (4, 2))
b = np.random.randint(1, 11, size = (2, 3))

In [25]:
pdt = np.matmul(a, b)
pdt

array([[26, 14, 26],
       [87, 43, 97],
       [67, 33, 75],
       [22, 13, 19]])

In [27]:
pdt.T

array([[26, 87, 67, 22],
       [14, 43, 33, 13],
       [26, 97, 75, 19]])

In [28]:
sqr =  np.arange(1, 17)
sqr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [29]:
sqRoot = np.sqrt(sqr)

In [30]:
sqRoot

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        ])

In [32]:
np.savetxt('sqroot.csv', sqRoot, delimiter=',')

In [36]:
np.savetxt('sqRoot.csv', np.column_stack((sqr, sqRoot)), 
           delimiter = ',', 
           header='NUM, SQROOT', 
           comments='',
           fmt='%d, %.2f')