In [9]:
import numpy as np

In [11]:
arr1 = np.random.randint(1, 6, size=(4, 2))

In [13]:
arr1

array([[3, 5],
       [2, 1],
       [5, 2],
       [2, 3]])

In [15]:
arr2 = np.random.randint(10, 15, size=(2, 3))

In [17]:
arr2

array([[11, 13, 11],
       [12, 11, 11]])

In [19]:
pdt = np.matmul(arr1, arr2)

In [21]:
pdt

array([[93, 94, 88],
       [34, 37, 33],
       [79, 87, 77],
       [58, 59, 55]])

In [23]:
np.transpose(pdt)

array([[93, 34, 79, 58],
       [94, 37, 87, 59],
       [88, 33, 77, 55]])