In [1]:
import numpy as np

In [2]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
np.random.randint(1, 10, (3, 3))

array([[4, 6, 2],
       [6, 8, 3],
       [4, 9, 5]])

In [13]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
a.ndim

1

In [16]:
a.shape

(3,)

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
c.ndim

2

In [20]:
c.shape

(3, 3)

In [28]:
d = np.array([1, 1.25, 45, 77.5, bool(0)])

In [30]:
d.itemsize

8

In [31]:
e = np.array([1, 2, 3, 4, 5])

In [32]:
e.itemsize

4

In [33]:
r = np.random.randint(50, 100, size=(5, 5))

In [34]:
r

array([[65, 76, 80, 99, 66],
       [59, 93, 68, 97, 52],
       [69, 75, 93, 51, 61],
       [67, 82, 70, 55, 92],
       [67, 50, 97, 54, 52]])

In [40]:
(r[1:4, 1:4]) = 0

In [41]:
r

array([[65, 76, 80, 99, 66],
       [59,  0,  0,  0, 52],
       [69,  0,  0,  0, 61],
       [67,  0,  0,  0, 92],
       [67, 50, 97, 54, 52]])

In [42]:
a.T

array([1, 2, 3])

In [43]:
b.T

array([[4, 7],
       [5, 8],
       [6, 9]])

In [45]:
np.genfromtxt('data.csv', delimiter=';', comments='#')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [48]:
sqr = np.arange(1, 17)
sqroot = np.sqrt(sqr)

In [49]:
np.savetxt('sqrROot', sqroot, delimiter=';')

In [57]:
m1 = np.random.randint(5, 25, size=(4, 2))


# tr = m1*m2
m1

array([[ 7, 11],
       [21, 23],
       [11, 23],
       [ 5, 24]])

In [58]:
m2 = np.random.randint(1, 15, size=(2, 3))


In [60]:
x = np.matmul(m1, m2)
x

array([[153, 104, 145],
       [339, 262, 335],
       [309, 192, 285],
       [303, 155, 265]])

In [61]:
x.T

array([[153, 339, 309, 303],
       [104, 262, 192, 155],
       [145, 335, 285, 265]])