# NumPy
### NumPy aims to provide an array object that is upto 50x faster than traditional Python lists

# Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
This behavior is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [47]:
import numpy as np
import pandas as pd

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [3]:
np.__version__

'1.26.4'

In [5]:
type(a1)

numpy.ndarray

type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

In [6]:
a2 = np.array((1, 5, 8, 9))
a2

array([1, 5, 8, 9])

0-D arrays: Scalors
1-D arrays: Vectors
2-D arrays: Matrices
3-D arrays: Tensors

In [9]:
# Check number of dimensions
a = np.array(42)
a1 = np.array([4])
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(a1.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
1
2
3


In [18]:
d5 = np.array([1, 4, 5, 7, 8]).reshape(5, )
d5
# The ndim attribute in NumPy is used to return the number of dimensions of an array, not to define the shape of an array. To define the shape of an array, you can use the reshape() method or specify the shape directly when creating an array using functions like np.zeros(), np.ones(), or np.random.rand().

array([1, 4, 5, 7, 8])

In [20]:
# ndmin
np.array([1, 55, 88], ndmin=5)

array([[[[[ 1, 55, 88]]]]])

### Access array elements

In [22]:
a3 = np.array([4, 5, 8, 1])
a3

array([4, 5, 8, 1])

In [23]:
a3[1]

5

In [24]:
a4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
a4[1, 4]

10

In [26]:
# Slicing array
a5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a5[1, 1:3]

array([7, 8])

In [28]:
# printing 2nd element from both subarrays
a6 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
(a6[0:2, 2])

array([3, 8])

### Reshaping

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
# 1st arguement - number of blocks
# 2nd arguement - number of rows per block
# 3rd arguement = numbers of elements per row
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## Converting a 2D array to 1D

In [31]:
a6 = np.array([[1, 2, 3], [4, 5, 6]])
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a6.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [33]:
# Iterating over 1-D array
a7 = np.array([1, 2, 3])

for x in a7:
  print(x)

1
2
3


In [34]:
# Iterating over 2-D array
a8 = np.array([[1, 2, 3], [4, 5, 6]])
for x in a8:
    for y in x:
        print(y)


1
2
3
4
5
6


In [36]:
ar1 = np.array([1, 2, 3])
ar2 = np.array([5, 6, 7])

ar12 = np.concatenate((ar1, ar2))
ar12

array([1, 2, 3, 5, 6, 7])

In [38]:
a9 = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(a9, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [40]:
a10 = np.arange(50).reshape(10, 5)
a10

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [41]:
a11 = np.random.randint(9, size=(3, 3))
a11

array([[3, 5, 6],
       [3, 0, 3],
       [4, 1, 6]])

### Eigen values and Eigen vectors

In [44]:
eiVa, eiVe = np.linalg.eig(a11)

In [52]:
eval = pd.DataFrame(eiVa, columns=['EigenVal'])
evec = pd.DataFrame(eiVe, columns=[f'Eigenvector {i+1}' for i in range(eiVe.shape[1])])
res = pd.concat([eval, evec], axis=1)
res

EigenVal  Eigenvector 1  Eigenvector 2  Eigenvector 3
0  11.007084      -0.692839      -0.786939      -0.693158
1  -2.710867      -0.359243       0.539512      -0.400668
2   0.703783      -0.625234       0.299424       0.599164