In [1]:
import numpy as np

In [2]:
sales = np.random.randint(1, 50, size=10)
sales

array([ 2, 21, 24, 43, 41,  6, 38, 13, 13, 12])

In [4]:
fifth_day_sales = sales[4]
fifth_day_sales

41

In [5]:
first_five_days = sales[:5]
first_five_days

array([ 2, 21, 24, 43, 41])

In [6]:
last_three_days = sales[-3:]
last_three_days

array([13, 13, 12])

In [7]:
increased_sales = sales+10
increased_sales

array([12, 31, 34, 53, 51, 16, 48, 23, 23, 22])

In [8]:
discount_sales = sales - (sales * 0.1)
discount_sales

array([ 1.8, 18.9, 21.6, 38.7, 36.9,  5.4, 34.2, 11.7, 11.7, 10.8])

In [10]:
total_sales = sales.sum()
total_sales

213

In [14]:
average_sales = np.mean(sales)
average_sales

21.3

In [16]:
max_sales = sales.max()
max_sales

43

In [17]:
sales_min = sales.min()
sales_min

2

In [18]:
reshapeSales = sales.reshape(2, 5)
reshapeSales

array([[ 2, 21, 24, 43, 41],
       [ 6, 38, 13, 13, 12]])

In [21]:
above_35 = sales[sales>35]
above_35

array([43, 41, 38])

In [22]:
high_sales = sales>35
high_sales

array([False, False, False,  True,  True, False,  True, False, False,
       False])