In [1]:
import numpy as np

In [4]:
myL = [1, 2, 3]
print(type(myL))

<class 'list'>


In [6]:
myA = np.array([1, 2, 3])
print(type(myA))

<class 'numpy.ndarray'>


In [7]:
myMatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.array(myMatrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.random.rand(2)

array([0.35071705, 0.59597144])

In [14]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [15]:
print(np.linspace(0,5,21))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [16]:
print(np.random.rand(2))

[0.44738263 0.98683514]


In [18]:
np.random.rand(5,5)

array([[0.05077091, 0.67659215, 0.84442398, 0.71880263, 0.33719674],
       [0.16829494, 0.72933808, 0.86095302, 0.11400788, 0.63257557],
       [0.69560254, 0.59270024, 0.47896269, 0.4456436 , 0.70498966],
       [0.15978888, 0.82553234, 0.88793826, 0.41571461, 0.90461869],
       [0.2790393 , 0.37913945, 0.91079973, 0.76118147, 0.14366084]])

In [19]:
np.random.randint(1,100)

94

In [20]:
np.random.randint(1,100,10)

array([90, 15,  7, 80, 42, 11, 29, 81, 22,  6])

In [21]:
np.random.seed(77)

In [22]:
# seeding
np.random.seed(77)
np.random.rand(4)

array([0.91910903, 0.6421956 , 0.75371223, 0.13931457])

In [23]:
# Storing
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([32, 39, 44, 19, 32, 36, 36, 47, 14, 15])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.max()

47

In [27]:
ranarr.argmax()

7

In [28]:
ranarr.min()

14

In [29]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[8]

8

In [31]:
arr[1:5]

array([1, 2, 3, 4])

In [32]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [33]:
arr[0:5] = 100

In [34]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [37]:
# change slice
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [40]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
# conditional logic
arr2 = np.arange(1, 11)

In [44]:
bool_arr2 = arr2>4

In [45]:
bool_arr2 # will only give true, false array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr2[bool_arr2] # will print the elements that are true for the condition 

array([ 5,  6,  7,  8,  9, 10])

In [60]:
a = np.arange(1, 11)

In [61]:
a + a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
a * a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [64]:
a / a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
1/ arr

array([0.01010101, 0.01010101, 0.01010101, 0.01010101, 0.01010101,
       0.01010101, 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [66]:
arr**3

array([970299, 970299, 970299, 970299, 970299, 970299,    216,    343,
          512,    729,   1000], dtype=int32)

In [67]:
np.sqrt(arr)

array([9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
       9.94987437, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [68]:
np.exp(arr)

array([9.88903032e+42, 9.88903032e+42, 9.88903032e+42, 9.88903032e+42,
       9.88903032e+42, 9.88903032e+42, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [69]:
np.sin(arr)

array([-0.99920683, -0.99920683, -0.99920683, -0.99920683, -0.99920683,
       -0.99920683, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [70]:
np.log(arr)

array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985,
       4.59511985, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [71]:
arr.sum()

634

In [72]:
arr.mean()

57.63636363636363

In [73]:
arr.max()

99

In [74]:
arr.min()

6

In [75]:
arr.var()

2054.0495867768595

In [76]:
arr.std()

45.32162383208328

In [78]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr_2d.shape

(3, 4)

In [80]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [81]:
arr_2d.sum(axis=1)

array([10, 26, 42])

In [82]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones