In [2]:
import scipy 
import numpy as np

In [15]:
m1 = np.random.randint(1, 10, size=(3, 3))
m1

array([[1, 5, 7],
       [7, 1, 4],
       [3, 7, 7]])

In [17]:
determinant = scipy.linalg.det(m1)
determinant

116.00000000000003

In [19]:
inverse = scipy.linalg.inv(m1)
inverse

array([[-0.18103448,  0.12068966,  0.11206897],
       [-0.31896552, -0.12068966,  0.38793103],
       [ 0.39655172,  0.06896552, -0.29310345]])

In [21]:
# transpose
m1.T

array([[1, 7, 3],
       [5, 1, 7],
       [7, 4, 7]])

In [26]:
#  SVD - Singular Value Decomposition (SVD) 
svd = scipy.linalg.svd(m1)
svd

(array([[-0.5709194 ,  0.38103838, -0.72722816],
        [-0.42617805, -0.89463352, -0.13417576],
        [-0.7017288 ,  0.23332513,  0.67315383]]),
 array([14.55309457,  5.86159374,  1.35983722]),
 array([[-0.3888762 , -0.56296457, -0.72927786],
        [-0.88396111,  0.45104359,  0.12317648],
        [ 0.25959211,  0.69255366, -0.6730389 ]]))

In [27]:
# eigen values
eig = scipy.linalg.eig(m1)
eig

(array([14.36534287+0.j        , -2.68267144+0.93715738j,
        -2.68267144-0.93715738j]),
 array([[ 0.54121682+0.j        , -0.11823898+0.16802656j,
         -0.11823898-0.16802656j],
        [ 0.48833293+0.j        ,  0.81018879+0.j        ,
          0.81018879-0.j        ],
        [ 0.68455482+0.j        , -0.53899657-0.10422788j,
         -0.53899657+0.10422788j]]))